version: '3.8'

services:
  book-management-be:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=book-management-db
      - DB_USER=root
      - DB_PASSWORD=P@ssw0rd
      - DB_NAME=book_database
    depends_on:
      - book-management-db

  book-management-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: book_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
